"""
Pick representative product images for each quiz answer card, straight from catalog.json.
Output: frontend/src/cardImages.js  (card label -> image URL, ?width=400 for fast load)

Run:  python pick_card_images.py
"""
import json, sys, io, re
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

CATALOG = "frontend/public/catalog.json"
catalog = json.load(open(CATALOG, encoding="utf-8"))

def w400(url):
    if not url: return url
    # Shopify CDN: insert _400x before extension, or append ?width=400
    return url + ("&" if "?" in url else "?") + "width=400"

# (label, dimension, required values, gender?) — first product matching ALL gets the card image.
# gender (4th elem) optional: constrains which gender's photo represents the card.
CARDS = [
    # gender
    ("Men", "gender", ["men"]), ("Women", "gender", ["women"]),
    # category — MEN
    ("Shirts", "category", ["shirt"], "men"), ("T-shirts", "category", ["tshirt"], "men"),
    ("Polos", "category", ["polo"], "men"), ("Jeans & Trousers", "category", ["jeans"], "men"),
    ("Winter wear", "category", ["jacket", "hoodie", "sweatshirt"], "men"),
    # category — WOMEN
    ("Tops", "category", ["top", "tshirt"], "women"),
    ("Dresses & Co-ords", "category", ["dress", "coord"], "women"),
    ("Bottoms", "category", ["jeans", "trousers"], "women"),
    # occasion (pair with a common category for a clean photo)
    ("Chill", "occasion", ["casual"]), ("Smart", "occasion", ["smart_casual"]),
    ("Night out", "occasion", ["street"]), ("Sharp", "occasion", ["formal"]),
    # fit
    ("Fitted", "fit", ["slim"]), ("True to size", "fit", ["regular"]), ("Loose", "fit", ["oversized"]),
    # pattern
    ("Clean", "pattern", ["solid"]), ("Texture", "pattern", ["textured"]),
    ("Stripes", "pattern", ["stripe"]), ("Checks", "pattern", ["check"]), ("Printed", "pattern", ["print"]),
    # color buckets
    ("Neutrals", "color", ["black"]), ("Earthy", "color", ["olive"]),
    ("Blues", "color", ["blue"]), ("Bold", "color", ["red"]),
    # band
    ("Under ₹1.2k", "band", ["budget"]), ("₹1.2k–2k", "band", ["mid"]), ("Premium", "band", ["premium"]),
    # sleeve / fabric
    ("Half", "sleeve", ["half"]), ("Full", "sleeve", ["full"]),
    ("Breezy", "fabric", ["linen"]), ("Structured", "fabric", ["denim"]), ("Cozy", "fabric", ["knit"]),
]

def has(p, dim, vals):
    pv = p.get(dim)
    pv = pv if isinstance(pv, list) else [pv]
    return any(v in pv for v in vals)

# attribute dims read best on a clean, recognizable garment (so the photo *shows* the attribute).
# category/gender dims are about the garment itself, so no base constraint.
BASE_DIMS = {"occasion", "fit", "pattern", "color", "fabric", "band"}
BASE_CATS = ["shirt", "tshirt", "polo"]

def pick_image(dim, vals, gender):
    base = (dim in BASE_DIMS)
    # relaxation ladder: most representative first, then loosen until something matches
    ladders = []
    if base:
        ladders.append(lambda p: has(p, dim, vals) and p.get("category") in BASE_CATS and p.get("gender") == "men")
        ladders.append(lambda p: has(p, dim, vals) and p.get("category") in BASE_CATS)
    if gender:
        ladders.append(lambda p: has(p, dim, vals) and p.get("gender") == gender)
    ladders.append(lambda p: has(p, dim, vals))
    for cond in ladders:
        m = next((p for p in catalog if p.get("image") and cond(p)), None)
        if m:
            return m
    return None

# nested by question id (dimension) -> { card label: image url } to match App.jsx
out = {}
n = 0
for card in CARDS:
    label, dim, vals = card[0], card[1], card[2]
    gender = card[3] if len(card) > 3 else None
    match = pick_image(dim, vals, gender)
    out.setdefault(dim, {})
    if match:
        out[dim][label] = w400(match["image"])
        n += 1
        print(f"  {dim:9s} {label:18s} <- {match['title'][:38]}  ({match.get('gender')}/{match.get('category')})")
    else:
        print(f"  {dim:9s} {label:18s} <- (no match)")

js = "// auto-generated by pick_card_images.py — real product photos per answer card\n"
js += "// shape: { questionId: { cardLabel: imageUrl } }\n"
js += "export const CARD_IMAGES = " + json.dumps(out, ensure_ascii=False, indent=2) + ";\n"
open("frontend/src/cardImages.js", "w", encoding="utf-8").write(js)
print(f"\nwrote frontend/src/cardImages.js ({n} cards across {len(out)} questions)")
