// auto-generated by pick_card_images.py — real product photos per answer card
// shape: { questionId: { cardLabel: imageUrl } }
export const CARD_IMAGES = {
  "gender": {
    "Men": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_014c1669-30fd-44be-a3bb-fe83013ebd18.jpg?v=1779819953&width=400",
    "Women": "https://cdn.shopify.com/s/files/1/0653/0541/1684/files/technicolor-oversized-t-shirt-xs-bonkerscorner-store-33709563936868.jpg?v=1728981177&width=512&width=400"
  },
  "category": {
    "Shirts": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_014c1669-30fd-44be-a3bb-fe83013ebd18.jpg?v=1779819953&width=400",
    "T-shirts": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4rn042-01_1.jpg?v=1774804526&width=400",
    "Polos": "https://cdn.shopify.com/s/files/1/0517/2939/9964/files/POL-SLICE-TL_1.jpg?v=1757334799&width=400",
    "Jeans & Trousers": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_db826d42-f0b8-4525-87db-181ffefbf64d.jpg?v=1781196919&width=400",
    "Winter wear": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_a7f5e936-1f1d-4363-8c53-55b4f060ff15.jpg?v=1779985930&width=400",
    "Tops": "https://cdn.shopify.com/s/files/1/0653/0541/1684/files/technicolor-oversized-t-shirt-xs-bonkerscorner-store-33709563936868.jpg?v=1728981177&width=512&width=400",
    "Dresses & Co-ords": "https://cdn.shopify.com/s/files/1/0653/0541/1684/files/BonkersCornerset8-12-202540578.jpg?v=1780554335&width=512&width=400",
    "Bottoms": "https://cdn.shopify.com/s/files/1/0653/0541/1684/files/DeepBlueRelaxedFitJeans_8.jpg?v=1781001079&width=512&width=400"
  },
  "occasion": {
    "Chill": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_fc26fab0-eaa8-4f4f-94df-6fce020402ee.jpg?v=1779027371&width=400",
    "Smart": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_014c1669-30fd-44be-a3bb-fe83013ebd18.jpg?v=1779819953&width=400",
    "Night out": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4rn042-01_1.jpg?v=1774804526&width=400",
    "Sharp": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_da817194-91d0-4e7f-8bb4-63a13348707e.jpg?v=1780310494&width=400"
  },
  "fit": {
    "Fitted": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_8f9b0b52-a6f1-4b68-b401-b061faabb1d9.jpg?v=1781197016&width=400",
    "True to size": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_014c1669-30fd-44be-a3bb-fe83013ebd18.jpg?v=1779819953&width=400",
    "Loose": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4rn042-01_1.jpg?v=1774804526&width=400"
  },
  "pattern": {
    "Clean": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_014c1669-30fd-44be-a3bb-fe83013ebd18.jpg?v=1779819953&width=400",
    "Texture": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4lshs002-06_1.jpg?v=1779725233&width=400",
    "Stripes": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_65dae5fb-d045-4c87-8441-52293b09dbc4.jpg?v=1781025687&width=400",
    "Checks": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_fc26fab0-eaa8-4f4f-94df-6fce020402ee.jpg?v=1779027371&width=400",
    "Printed": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4rn042-01_1.jpg?v=1774804526&width=400"
  },
  "color": {
    "Neutrals": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_f1e3419c-6434-48e3-8b14-77754850cad4.jpg?v=1779819941&width=400",
    "Earthy": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_014c1669-30fd-44be-a3bb-fe83013ebd18.jpg?v=1779819953&width=400",
    "Blues": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_da817194-91d0-4e7f-8bb4-63a13348707e.jpg?v=1780310494&width=400",
    "Bold": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_0ffd0f93-d811-486d-a874-e8d88d4bdf1d.jpg?v=1776787582&width=400"
  },
  "band": {
    "Under ₹1.2k": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/146f3abf31687dead1d29e229870feeb.webp?v=1718971781&width=400",
    "₹1.2k–2k": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_014c1669-30fd-44be-a3bb-fe83013ebd18.jpg?v=1779819953&width=400",
    "Premium": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/4mlx1242-01_1.jpg?v=1779725289&width=400"
  },
  "sleeve": {
    "Half": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_014c1669-30fd-44be-a3bb-fe83013ebd18.jpg?v=1779819953&width=400",
    "Full": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_8f9b0b52-a6f1-4b68-b401-b061faabb1d9.jpg?v=1781197016&width=400"
  },
  "fabric": {
    "Breezy": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_65dae5fb-d045-4c87-8441-52293b09dbc4.jpg?v=1781025687&width=400",
    "Structured": "https://cdn.shopify.com/s/files/1/0517/2939/9964/files/TBH-BUNOL-BL__1.jpg?v=1775136734&width=400",
    "Cozy": "https://cdn.shopify.com/s/files/1/0420/7073/7058/files/1_956088e4-63dd-4780-8ad4-84533091eb74.jpg?v=1780407538&width=400"
  }
};
